/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      colors: {
        bg:          '#09090f',
        surface:     '#0f0f1a',
        elevated:    '#141428',
        border:      'rgba(255,255,255,0.07)',
        'border-md': 'rgba(255,255,255,0.12)',
        accent:      '#7c3aed',
        accentLight: '#a78bfa',
        accentBlue:  '#3b82f6',
        'text-1':    '#f0eeff',
        'text-2':    '#8b8faa',
        'text-3':    '#52566e',
      },
      animation: {
        'spin-slow':    'spin 3s linear infinite',
        'spin-slower':  'spin 8s linear infinite',
        'spin-reverse': 'spinReverse 5s linear infinite',
        'fade-in':      'fadeIn 0.5s ease-in-out',
        'slide-up':     'slideUp 0.4s ease-out',
        'slide-up-fade':'slideUpFade 0.5s ease-out forwards',
        'pulse-glow':   'pulseGlow 2s ease-in-out infinite',
        'float':        'float 7s ease-in-out infinite',
        'float-slow':   'float 11s ease-in-out infinite',
        'float-med':    'float 9s ease-in-out infinite',
        'shimmer':      'shimmer 3s linear infinite',
        'bounce-in':    'bounceIn 0.5s cubic-bezier(0.34,1.56,0.64,1) both',
        'pulse-ring':   'pulseRing 2.5s ease-out infinite',
      },
      keyframes: {
        fadeIn:      { '0%': { opacity: '0' },          '100%': { opacity: '1' } },
        slideUp:     { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideUpFade: { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        pulseGlow:   { '0%,100%': { boxShadow: '0 0 15px rgba(124,58,237,0.3)' }, '50%': { boxShadow: '0 0 40px rgba(124,58,237,0.7)' } },
        float:       { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-22px)' } },
        shimmer:     { '0%': { backgroundPosition: '-200% center' }, '100%': { backgroundPosition: '200% center' } },
        bounceIn:    { '0%': { opacity: '0', transform: 'scale(0.75)' }, '70%': { transform: 'scale(1.05)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        pulseRing:   { '0%': { transform: 'scale(1)', opacity: '0.6' }, '100%': { transform: 'scale(1.6)', opacity: '0' } },
        spinReverse: { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(-360deg)' } },
      },
    },
  },
  plugins: [],
};
